# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iC949jYe5uDWypAh_18uM1VQXiivW5-o
"""

# STEP 1: Upload CSV File
from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))

# Basic Info
print("First 5 rows:\n", df.head())
print("\n Shape:", df.shape)
print("\n Data Types & Null Values:\n")
df.info()
print("\n Missing Values:\n", df.isnull().sum())
print("\n Descriptive Stats:\n", df.describe())

# Set plot style
sns.set(style="whitegrid")

# 1. Histogram - Age
plt.figure(figsize=(8, 5))
sns.histplot(df['Age'].dropna(), kde=True, bins=30, color='skyblue')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

# 2. Boxplot - Age vs Survival
plt.figure(figsize=(8, 5))
sns.boxplot(x='Survived', y='Age', data=df, palette="Set2")
plt.title('Survival vs Age')
plt.xlabel('Survived (0 = No, 1 = Yes)')
plt.ylabel('Age')
plt.show()

# 3. Countplot - Pclass vs Survival
plt.figure(figsize=(6, 4))
sns.countplot(x='Pclass', hue='Survived', data=df, palette="Set1")
plt.title('Passenger Class vs Survival')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.legend(title='Survived')
plt.show()

# 4. Heatmap - Correlation
plt.figure(figsize=(10, 6))
# Calculate correlation only for numeric columns
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

# 5. Pairplot (Optional - takes time)
sns.pairplot(df[['Survived', 'Age', 'Fare', 'Pclass']].dropna(), hue='Survived')
plt.suptitle('Pairplot of Selected Features', y=1.02)
plt.show()